export const INITIAL_LAYOUT = 'modules'
export const PICTOGRAMS_LAYOUT = 'PICTOGRAMS_LAYOUT'

export const CHANGE_PICTOGRAMS_KEYWORD = 'CHANGE_PICTOGRAMS_KEYWORD'

export const PICTOGRAMS_REQUEST = 'PICTOGRAMS_REQUEST'
export const PICTOGRAMS_SUCCESS = 'PICTOGRAMS_SUCCESS'
export const PICTOGRAMS_FAILURE = 'PICTOGRAMS_FAILURE'

export const LOCALE_CHANGE = 'LOCALE_CHANGE'

export const KEYWORDS_REQUEST = 'KEYWORDS_REQUEST'
export const KEYWORDS_SUCCESS = 'KEYWORDS_SUCCESS'
export const KEYWORDS_FAILURE = 'KEYWORDS_FAILURE'

export const SHOW_FILTER = 'SHOW_FILTER'
export const TOGGLE_FILTER = 'TOGGLE_FILTER'
